package jp.co.timepage.mybatis.mapper;

import jp.co.timepage.mybatis.entity.Fruit;

public interface FruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline.Fruit
     *
     * @mbggenerated Wed Sep 05 02:26:08 JST 2018
     */
    int insert(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline.Fruit
     *
     * @mbggenerated Wed Sep 05 02:26:08 JST 2018
     */
    int insertSelective(Fruit record);
}