package jp.co.timepage.mybatis.mapper;

import java.util.List;

import jp.co.timepage.mybatis.entity.Timepage;
import jp.co.timepage.mybatis.entity.TimepageKey;

public interface TimepageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline.TimePage
     *
     * @mbggenerated Wed Sep 05 02:26:08 JST 2018
     */
    int deleteByPrimaryKey(TimepageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline.TimePage
     *
     * @mbggenerated Wed Sep 05 02:26:08 JST 2018
     */
    int insert(Timepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline.TimePage
     *
     * @mbggenerated Wed Sep 05 02:26:08 JST 2018
     */
    int insertSelective(Timepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline.TimePage
     *
     * @mbggenerated Wed Sep 05 02:26:08 JST 2018
     */
    Timepage selectByPrimaryKey(TimepageKey key);


    List<Timepage> selectByPrimaryList(TimepageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline.TimePage
     *
     * @mbggenerated Wed Sep 05 02:26:08 JST 2018
     */
    int updateByPrimaryKeySelective(Timepage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeline.TimePage
     *
     * @mbggenerated Wed Sep 05 02:26:08 JST 2018
     */
    int updateByPrimaryKey(Timepage record);
}