package jp.co.timepage.mybatis.entity;

public class Timepage extends TimepageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.TimePage.title
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.TimePage.content_out
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    private String contentOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.TimePage.content_main
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    private String contentMain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.TimePage.title
     *
     * @return the value of timeline.TimePage.title
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.TimePage.title
     *
     * @param title the value for timeline.TimePage.title
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.TimePage.content_out
     *
     * @return the value of timeline.TimePage.content_out
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public String getContentOut() {
        return contentOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.TimePage.content_out
     *
     * @param contentOut the value for timeline.TimePage.content_out
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public void setContentOut(String contentOut) {
        this.contentOut = contentOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.TimePage.content_main
     *
     * @return the value of timeline.TimePage.content_main
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public String getContentMain() {
        return contentMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.TimePage.content_main
     *
     * @param contentMain the value for timeline.TimePage.content_main
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public void setContentMain(String contentMain) {
        this.contentMain = contentMain;
    }
}