package jp.co.timepage.mybatis.entity;

public class TimepageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.TimePage.user_id
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.TimePage.time_year
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    private String timeYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timeline.TimePage.time_month
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    private String timeMonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.TimePage.user_id
     *
     * @return the value of timeline.TimePage.user_id
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.TimePage.user_id
     *
     * @param userId the value for timeline.TimePage.user_id
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.TimePage.time_year
     *
     * @return the value of timeline.TimePage.time_year
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public String getTimeYear() {
        return timeYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.TimePage.time_year
     *
     * @param timeYear the value for timeline.TimePage.time_year
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public void setTimeYear(String timeYear) {
        this.timeYear = timeYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timeline.TimePage.time_month
     *
     * @return the value of timeline.TimePage.time_month
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public String getTimeMonth() {
        return timeMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timeline.TimePage.time_month
     *
     * @param timeMonth the value for timeline.TimePage.time_month
     *
     * @mbggenerated Wed Aug 29 00:41:40 JST 2018
     */
    public void setTimeMonth(String timeMonth) {
        this.timeMonth = timeMonth;
    }
}